### ISSUE TITLE
Can you find alexa ranks of a 50k list of website domains?

### ISSUE THREAD

**Issue by Marketingguru** [elhardoum/top-wordpress-sites#1]
I have a 50k list of website urls and I was wondering if you had something that can find the alexa rank of them all.

**Comment by elhardoum** [comment]
Hello, sorry for the delay.

Yes, Alexa offers some kind of API but I am not sure about the usage limitations, so you might want to either add some sleep time between each API request (until #50k) or just go ahead with consequences.

Here's some basic python code to get you started
```python
#!/usr/bin/env python
import urllib, sys, re
xml = urllib.urlopen('http://data.alexa.com/data?cli=10&dat=s&url=%s'%sys.argv[1]).read()
try: rank = int(re.search(r'RANK="(\d+)"', xml).groups()[0])
except: rank = -1
print 'Your rank for %s is %d!\n' % (sys.argv[1], rank)
```

If you need help with it let me know.

Best,
Samuel
